stages:
  - review
  - staging
#  - production

review:
  stage: review
  script:
    - rsync -av --delete * /home/preview/$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG
  environment:
    name: Preview/$CI_BUILD_REF_NAME
    url: http://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.timmxware.fr/
    on_stop: stop_review
  only:
    - branches
  except:
    - master


stop_review:
  stage: review
  script:
    - rm -rf * /home/preview/$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG
  variables:
    GIT_STRATEGY: none
  when: manual
  environment:
    name: Preview/$CI_BUILD_REF_NAME
    action: stop

staging:
  stage: staging
  script:
    - rsync -av --delete * /home/preview/$CI_PROJECT_NAME
  environment:
    name: Préprod
    url: http://$CI_PROJECT_NAME.timmxware.fr/
  only:
    - master


#production:
#  stage: production
#  script:
#    - rsync -av --delete * /srv/nginx/pages/production
#  environment:
#    name: Production
#    url: http://$CI_PROJECT_NAME.gitlab.local/
#  when: manual
#  only:
#    - master
