deploy as preview app:
  stage: test
  except:
    - master
  when: manual
  script: echo $CI_PROJECT_DIR
  environment:
    name: Features/$CI_BUILD_REF_NAME
    url: http://$CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG.gitlab.local/
    on_stop: stop_preview_app
  before_script:
    - mkdir $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG
    - cd $CI_PROJECT_NAME-$CI_ENVIRONMENT_SLUG

stop_preview_app:
  stage: test
  except:
    - master
  when: manual
  variables:
    GIT_STRATEGY: none
  script: echo "good bye"
  environment:
    name: Features/$CI_BUILD_REF_NAME
    action: stop

production app:
  stage: deploy
  when: manual
  script: echo $CI_PROJECT_DIR
  only:
    - master
  environment:
    name: Master
    url: http://$CI_PROJECT_NAME.gitlab.local/
  before_script:
  - mkdir $CI_PROJECT_NAME
  - cd $CI_PROJECT_NAME
